Repository Ensembl/ensembl-client, pull requests merged in 2019-07, with the labels that each got.

#110 Fix "not found" message for SpeciesSearchField
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.test.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.tsx
  src/ensembl/src/content/app/species-selector/constants/speciesSelectorConstants.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorEpics.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorReducer.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorSelectors.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorState.ts
Labels: bugfix

#115 Fix SpeciesSearchField tests
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.test.tsx
Labels: bugfix

#114 Add client-side setup to use Sentry for error tracking
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/services/error-service.ts
Labels: enhancement

#116 Update inialization flow for error-service
  src/ensembl/src/services/error-service.ts
Labels: enhancement

#112 Fix edge case for species search match
  src/ensembl/src/content/app/species-selector/components/species-search-match/SpeciesSearchMatch.tsx
Labels: bugfix

#113 Add analytics to species selector
  src/ensembl/config.ts
  src/ensembl/src/analyticsHelper.ts
  src/ensembl/src/analyticsMiddleware.ts
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/drawer/drawerActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/state/attributesAccordionActions.ts
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/state/filterAccordionActions.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadActions.ts
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.test.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.tsx
  src/ensembl/src/content/app/species-selector/speciesSelectorHelper.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorEpics.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorReducer.ts
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/header/headerActions.ts
  src/ensembl/src/services/analytics-service.ts
  src/ensembl/typings/config.d.ts
Labels: enhancement

#108 Browser messaging service
  .gitignore
  src/assets/browser/app/src/controller/global/activate.rs
  src/assets/browser/app/src/controller/global/app.rs
  src/assets/browser/app/src/controller/global/apprunner.rs
  src/assets/browser/app/src/controller/global/booting.rs
  src/assets/browser/app/src/controller/global/global.rs
  src/assets/browser/app/src/controller/global/mod.rs
  src/assets/browser/app/src/controller/input/action.rs
  src/assets/browser/app/src/controller/input/direct.rs
  src/assets/browser/app/src/controller/input/eventqueue.rs
  src/assets/browser/app/src/controller/input/eventutil.rs
  src/assets/browser/app/src/controller/input/mod.rs
  src/assets/browser/app/src/controller/input/optical.rs
  src/assets/browser/app/src/controller/input/physics.rs
  src/assets/browser/app/src/controller/input/startup.rs
  src/assets/browser/app/src/controller/output/counter.rs
  src/assets/browser/app/src/controller/output/mod.rs
  src/assets/browser/app/src/controller/output/outputaction.rs
  src/assets/browser/app/src/controller/output/report.rs
  src/assets/browser/app/src/dom/appeventdata.rs
  src/assets/browser/app/src/dom/domutil.rs
  src/assets/browser/app/src/dom/event.rs
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/BrowserCogList.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-constants.ts
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-messaging-service.test.ts
  src/ensembl/src/content/app/browser/browser-messaging-service.ts
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/browserState.ts
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/zmenu/ZmenuController.tsx
  src/ensembl/src/content/app/browser/zmenu/mock-event-emitter.tsx
  src/ensembl/src/content/app/browser/zmenu/zmenu-types.ts
  src/ensembl/src/services/tests/storage-service.test.ts
  src/ensembl/src/services/window-service.ts
  src/ensembl/static/browser/browser-13bcc4dc08eb2ecb83433f02b3eb764b.wasm
  src/ensembl/static/browser/browser-bf0b557857ddcf52787fad05cae6757e.wasm
  src/ensembl/static/browser/browser.js
Labels: enhancement

#119 Feature/image button tooltips
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/shared/hooks/useHover.tsx
  src/ensembl/src/shared/image-button/ImageButton.scss
  src/ensembl/src/shared/image-button/ImageButton.test.tsx
  src/ensembl/src/shared/image-button/ImageButton.tsx
  src/ensembl/src/shared/tooltip/Tooltip.tsx
  src/ensembl/src/shared/tooltip/tooltip-constants.ts
Labels: feature

#124 Fix toggling of species use status
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorSelectors.ts
Labels: bugfix

#118 Fix drawer state
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-genome-selector/BrowserGenomeSelector.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/browser-tabs/BrowserTabs.tsx
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/drawer/drawerActions.ts
  src/ensembl/src/content/app/browser/drawer/drawerReducer.ts
  src/ensembl/src/content/app/browser/drawer/drawerSelectors.ts
  src/ensembl/src/content/app/browser/drawer/drawerState.ts
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelReducer.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelSelectors.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
Labels: bugfix

#125 Fix missing species on the header bar
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/genome/genomeActions.ts
Labels: bugfix

#129 Separate home and genome browser coordinates with commas
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-genome-selector/BrowserGenomeSelector.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/shared/helpers/numberFormatter.ts
Labels: enhancement

#127 Fix for browser tabs get hidden when track panel closed on large screens
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.scss
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-tabs/BrowserTabs.tsx
Labels: bugfix

#128 Update consumption of data from api/object and api/genome_search endpoints
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerGene.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerTranscript.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/species-selector/state/speciesSelectorEpics.ts
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/ens-object/ensObjectActions.ts
  src/ensembl/src/ens-object/ensObjectHelpers.ts
  src/ensembl/src/ens-object/ensObjectTypes.ts
  src/ensembl/src/shared/helpers/regionFormatter.ts
  src/ensembl/tests/data/ens-object/ens-objects.ts
  src/ensembl/tests/data/genome/genome-info.ts
  src/ensembl/tests/data/genome/genome-track-categories.ts
  src/ensembl/tests/fixtures/ens-object.ts
  src/ensembl/tsconfig.json
Labels: enhancement

#122 Feature/design changes
  src/ensembl/src/content/home/Home.scss
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/shared/button/Button.scss
Labels: feature
