Repository Ensembl/ensembl-client, pull requests merged in 2019-09, with the labels that each got.

#149 Remove refs from Browser component
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/BrowserCogList.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
Labels: refactoring

#155 Fix zmenu styles
  src/ensembl/src/content/app/browser/zmenu/Zmenu.scss
Labels: bugfix

#166 Update Home page
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/home/Home.scss
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/content/home/homePageSelectors.ts
  src/ensembl/src/shared/components/app-bar/AppBar.scss
  src/ensembl/src/shared/components/species-tab-bar/SpeciesTabBar.scss
  src/ensembl/src/shared/components/species-tab/SpeciesTab.scss
  src/ensembl/stories/shared-components/species-tab-bar/SpeciesTabBar.stories.tsx
Labels: bugfix, enhancement

#158 Refactor trackPanel state and update TrackPanelListItem
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.test.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelReducer.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelSelectors.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
  src/ensembl/src/root/rootReducer.ts
Labels: bugfix, refactoring

#167 Update packages and fix linting errors
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/browser-messaging-service.ts
  src/ensembl/src/content/app/custom-download/components/checkbox-grid/CheckboxGrid.test.tsx
  src/ensembl/src/content/app/custom-download/components/checkbox-with-selects/CheckboxWithSelects.test.tsx
  src/ensembl/src/content/app/custom-download/containers/content/result-holder/resultHolderHelper.ts
  src/ensembl/src/content/app/custom-download/containers/content/tab-buttons/TabButtons.tsx
  src/ensembl/src/content/app/custom-download/containers/header/CustomDownloadHeader.tsx
  src/ensembl/src/content/app/custom-download/state/attributes/attributesActions.ts
  src/ensembl/src/global/globalHelper.ts
  src/ensembl/src/services/error-service.ts
  src/ensembl/src/services/tests/api-service.test.ts
  src/ensembl/src/shared/components/select/Select.test.tsx
Labels: housekeeping, package update

#169 Fix initialization of track panel state
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelReducer.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
Labels: bugfix

#168 Fix broken track panel bar icon
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
Labels: bugfix
