Repository Ensembl/ensembl-client, pull requests merged in 2019-08, with the labels that each got.

#131 Feature/ss design changes
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.scss
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.scss
  src/ensembl/src/content/app/species-selector/containers/popular-species-panel/PopularSpeciesPanel.scss
  src/ensembl/src/content/app/species-selector/containers/species-search-panel/SpeciesSearchPanel.scss
  src/ensembl/src/styles/_settings.scss
Labels: enhancement

#134 Proxy api requests in local version of production server
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/server.js
Labels: enhancement

#133 Do not lower-case gene location info in BrowserBar
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.scss
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
Labels: bugfix

#126 Mock react-ga library during tests
  src/ensembl/jest.config.js
  src/ensembl/src/services/analytics-service.ts
  src/ensembl/tests/setup-enzyme.ts
  src/ensembl/tests/setup-jest.js
Labels: enhancement

#135 Update workbox config to prevent caching of html files
  src/ensembl/server.js
  src/ensembl/webpack/webpack.config.prod.js
Labels: bugfix

#141 Feature/more design tweaks
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.scss
  src/ensembl/src/content/app/custom-download/containers/pre-filters-panel/PreFilterPanel.scss
  src/ensembl/src/content/home/Home.scss
Labels: enhancement

#132 Use ImageButton in HeaderButtons (in masthead)
  src/ensembl/src/header/header-buttons/HeaderButtons.scss
  src/ensembl/src/header/header-buttons/HeaderButtons.test.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.tsx
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/services/window-service.ts
  src/ensembl/src/shared/tooltip/Tooltip.scss
  src/ensembl/src/shared/tooltip/Tooltip.tsx
  src/ensembl/src/shared/tooltip/tooltip-helper.ts
  src/ensembl/src/shared/utils/bringToFront.ts
  src/ensembl/src/shared/utils/tests/bringToFront.test.ts
  src/ensembl/static/img/header/user-grey.svg
  src/ensembl/stories/shared-components/tooltip/positioningStory.tsx
  src/ensembl/stories/shared-components/tooltip/variantsStory.tsx
Labels: enhancement

#136 Make track panel state of species indepedent
  src/ensembl/src/content/app/browser/BrowserCogList.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/browser-tabs/BrowserTabs.tsx
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/browserState.ts
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/PersonalData.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelDownloads.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelSearch.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelShare.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TracksManager.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelReducer.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelSelectors.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
  src/ensembl/src/genome/genomeTypes.ts
Labels: bugfix

#117 Feature/privacy banner
  src/ensembl/config.ts
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/root/Root.test.tsx
  src/ensembl/src/root/Root.tsx
  src/ensembl/src/shared/privacy-banner/PrivacyBanner.scss
  src/ensembl/src/shared/privacy-banner/PrivacyBanner.tsx
  src/ensembl/src/shared/privacy-banner/privacy-banner-service.test.ts
  src/ensembl/src/shared/privacy-banner/privacy-banner-service.ts
  src/ensembl/src/shared/privacy-banner/privacyConfig.ts
Labels: bugfix, enhancement

#143 Add overflow-x: scroll to launchbar
  src/ensembl/src/header/launchbar/Launchbar.scss
Labels: bugfix

#146 Close Track Configuration box by clicking anywhere - 206
  src/assets/browser/app/src/controller/input/user.rs
  src/ensembl/src/content/app/browser/BrowserCog.tsx
  src/ensembl/src/content/app/browser/BrowserCogList.tsx
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/browserState.ts
  src/ensembl/src/shared/hooks/tests/useOutsideClick.test.tsx
  src/ensembl/src/shared/hooks/useOutsideClick.tsx
  src/ensembl/static/browser/browser-13bcc4dc08eb2ecb83433f02b3eb764b.wasm
  src/ensembl/static/browser/browser-471e3f540c34e70bcb3cdb3985b0273b.wasm
  src/ensembl/static/browser/browser.js
Labels: feature

#142 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/custom-download/components/checkbox-with-textfields/CheckboxWithTextfields.test.tsx
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.scss
  src/ensembl/src/shared/components/inline-svg/InlineSvg.test.tsx
Labels: package update

#137 Add analytics to trackpanel
  src/ensembl/src/analyticsHelper.ts
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/BrowserCog.tsx
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersReducer.ts
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.tsx
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/header/headerActions.ts
  src/ensembl/src/services/analytics-service.ts
Labels: enhancement

#150 Remove condition upon environment from ZmenuContent (when showing links)
  src/ensembl/src/content/app/browser/zmenu/ZmenuContent.tsx
Labels: bugfix

#147 Remove Zurb Foundation
  src/ensembl/doc/architecture/decisions/0002-frontend-code.md
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/Content.scss
  src/ensembl/src/content/app/browser/Browser.scss
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/drawer/Drawer.scss
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.scss
  src/ensembl/src/header/Header.scss
  src/ensembl/src/header/account/Account.scss
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/root/Root.scss
  src/ensembl/src/styles/_breakpoints.scss
  src/ensembl/src/styles/_common.scss
  src/ensembl/src/styles/_normalize.scss
  src/ensembl/src/styles/_settings.scss
  src/ensembl/src/styles/main.scss
  src/ensembl/stories/shared-components/image-button/ImageButton.stories.scss
  src/ensembl/stylelint.config.js
Labels: refactoring

#151 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/stories/shared-components/tooltip/positioningStory.tsx
Labels: package update

#140 Add track highlight feature
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerTranscript.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelSelectors.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
  src/ensembl/src/content/app/browser/zmenu/ZmenuController.tsx
  src/ensembl/src/content/app/browser/zmenu/zmenu-types.ts
  src/ensembl/src/ens-object/ensObjectActions.ts
Labels: feature
