Repository Ensembl/ensembl-client, pull requests merged in 2019-10, with the labels that each got.

#173 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: package update

#175 Feature/use animation library
  src/assets/browser/Cargo.lock
  src/assets/browser/app/Cargo.lock
  src/assets/browser/app/Cargo.toml
  src/assets/browser/app/src/composit/scale.rs
  src/assets/browser/app/src/controller/animate/animate.rs
  src/assets/browser/app/src/controller/animate/mod.rs
  src/assets/browser/app/src/controller/global/apprunner.rs
  src/assets/browser/app/src/controller/global/windowstate.rs
  src/assets/browser/app/src/controller/input/action.rs
  src/assets/browser/app/src/controller/output/jumper.rs
  src/assets/browser/app/src/controller/output/mod.rs
  src/assets/browser/app/src/data/psychic.rs
  src/assets/browser/app/src/main.rs
  src/assets/browser/misc_algorithms/src/lib.rs
  src/assets/browser/misc_algorithms/src/zhoosh/README.md
  src/assets/browser/misc_algorithms/src/zhoosh/test.rs
  src/assets/browser/misc_algorithms/src/zhoosh/zhoosh.rs
  src/assets/browser/zhoosh/Cargo.lock
  src/assets/browser/zhoosh/Cargo.toml
  src/assets/browser/zhoosh/src/README.md
  src/assets/browser/zhoosh/src/lib.rs
  src/assets/browser/zhoosh/src/ops.rs
  src/assets/browser/zhoosh/src/runner.rs
  src/assets/browser/zhoosh/src/shapes.rs
  src/assets/browser/zhoosh/src/state.rs
  src/assets/browser/zhoosh/src/step.rs
  src/assets/browser/zhoosh/src/test.rs
  src/assets/browser/zhoosh/src/zhoosh.rs
  src/ensembl/static/browser/browser-2fcbea8c5ed5e40648c85402990ee427.wasm
  src/ensembl/static/browser/browser.js
Labels: enhancement

#174 Custom downloads layout changes
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.tsx
  src/ensembl/src/content/app/custom-download/CustomDownload.tsx
  src/ensembl/src/content/app/custom-download/components/checkbox-grid/CheckboxGrid.scss
  src/ensembl/src/content/app/custom-download/components/checkbox-grid/CheckboxGrid.tsx
  src/ensembl/src/content/app/custom-download/components/content-builder/ContentBuilder.scss
  src/ensembl/src/content/app/custom-download/components/content-builder/ContentBuilder.tsx
  src/ensembl/src/content/app/custom-download/components/info-card/CustomDownloadInfoCard.scss
  src/ensembl/src/content/app/custom-download/components/info-card/CustomDownloadInfoCard.tsx
  src/ensembl/src/content/app/custom-download/components/paste-or-upload/PasteOrUpload.scss
  src/ensembl/src/content/app/custom-download/containers/app-bar/CustomDownloadAppBar.tsx
  src/ensembl/src/content/app/custom-download/containers/content/CustomDownloadContent.scss
  src/ensembl/src/content/app/custom-download/containers/content/CustomDownloadContent.tsx
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/AttributesAccordion.scss
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/AttributesAccordion.tsx
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/sections/AttributesAccordionSection.tsx
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/sections/orthologues/Orthologues.tsx
  src/ensembl/src/content/app/custom-download/containers/content/customDownloadContentHelper.ts
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/FiltersAccordion.scss
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/FiltersAccordion.tsx
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/sections/FiltersAccordionSection.tsx
  src/ensembl/src/content/app/custom-download/containers/content/preview-card/PreviewCard.scss
  src/ensembl/src/content/app/custom-download/containers/content/preview-card/PreviewCard.tsx
  src/ensembl/src/content/app/custom-download/containers/content/preview-card/previewCardHelper.ts
  src/ensembl/src/content/app/custom-download/containers/content/preview-download/PreviewDownload.scss
  src/ensembl/src/content/app/custom-download/containers/content/preview-download/PreviewDownload.tsx
  src/ensembl/src/content/app/custom-download/containers/content/result-holder/ResultHolder.scss
  src/ensembl/src/content/app/custom-download/containers/content/result-holder/ResultHolder.tsx
  src/ensembl/src/content/app/custom-download/containers/content/result-holder/resultHolderHelper.ts
  src/ensembl/src/content/app/custom-download/containers/content/tab-buttons/TabButtons.scss
  src/ensembl/src/content/app/custom-download/containers/content/tab-buttons/TabButtons.tsx
  src/ensembl/src/content/app/custom-download/containers/header/CustomDownloadHeader.scss
  src/ensembl/src/content/app/custom-download/containers/header/CustomDownloadHeader.tsx
  src/ensembl/src/content/app/custom-download/containers/header/customDownloadHeaderHelper.ts
  src/ensembl/src/content/app/custom-download/containers/pre-filters-panel/PreFilterPanel.tsx
  src/ensembl/src/content/app/custom-download/sample-data/filters.ts
  src/ensembl/src/content/app/custom-download/services/custom-download-storage-service.tsx
  src/ensembl/src/content/app/custom-download/state/attributes/attributesActions.ts
  src/ensembl/src/content/app/custom-download/state/attributes/attributesReducer.ts
  src/ensembl/src/content/app/custom-download/state/attributes/attributesSelector.ts
  src/ensembl/src/content/app/custom-download/state/attributes/attributesState.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadActions.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadReducer.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadSelectors.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadState.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersActions.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersReducer.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersSelector.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersState.ts
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/src/services/storage-service.ts
  src/ensembl/src/shared/components/accordion/components/AccordionContext.tsx
  src/ensembl/src/shared/components/accordion/helpers/AccordionStore.ts
  src/ensembl/src/shared/components/overlay/Overlay.scss
  src/ensembl/src/shared/components/overlay/Overlay.tsx
  src/ensembl/static/img/shared/close.svg
Labels: bugfix, enhancement, feature

#182 Add textarea shared component
  src/ensembl/src/shared/components/textarea/Textarea.scss
  src/ensembl/src/shared/components/textarea/Textarea.test.tsx
  src/ensembl/src/shared/components/textarea/Textarea.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/textarea/Textarea.stories.scss
  src/ensembl/stories/shared-components/textarea/Textarea.stories.tsx
Labels: feature

#184 Update node version to the latest LTS (12.13.0)
  .gitlab-ci.yml
Labels: housekeeping

#183 Extract a generic Status type, from which ImageButtonStatus is derived
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/AttributesAccordion.tsx
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/FiltersAccordion.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.test.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.tsx
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.test.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/types/status.ts
  src/ensembl/stories/shared-components/badged-button/BadgedButton.stories.tsx
  src/ensembl/stories/shared-components/image-button/ImageButtonParent.stories.tsx
Labels: refactoring

#186 Remove RobotstxtPlugin from webpack
  src/ensembl/robots-txt.config.js
  src/ensembl/webpack/webpack.config.prod.js
Labels: bugfix

#187 Change default track config state for track labels to true
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
Labels: bugfix

#165 CSS breakpoints
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.scss
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/global/globalConfig.ts
  src/ensembl/src/global/globalHelper.ts
  src/ensembl/src/global/globalState.ts
  src/ensembl/src/header/Header.scss
  src/ensembl/src/styles/_breakpoints.scss
Labels: enhancement
