Repository Ensembl/ensembl-client, pull requests merged in 2019-12, with the labels that each got.

#207 Minor performance fixes
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-app-bar/BrowserAppBar.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/header/launchbar/LaunchbarContainer.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.test.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/components/image-button/ImageHolder.tsx
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.tsx
Labels: bugfix

#211 Change the way webpack configs are composed
  src/ensembl/README.md
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/webpack/.eslintrc.js
  src/ensembl/webpack/environments/environment-detector.js
  src/ensembl/webpack/environments/webpack.common.js
  src/ensembl/webpack/environments/webpack.config.dev.js
  src/ensembl/webpack/environments/webpack.config.prod.js
  src/ensembl/webpack/paths.js
  src/ensembl/webpack/presets/loadPresets.js
  src/ensembl/webpack/presets/webpack.analyse.js
  src/ensembl/webpack/webpack.common.js
  src/ensembl/webpack/webpack.config.dev.js
  src/ensembl/webpack/webpack.config.js
  src/ensembl/webpack/webpack.config.prod.js
Labels: infrastructure

#200 Feature/question button
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.tsx
  src/ensembl/src/shared/components/question-button/QuestionButton.scss
  src/ensembl/src/shared/components/question-button/QuestionButton.tsx
  src/ensembl/stories/shared-components/question-button/QuestionButton.stories.tsx
Labels: feature

#215 Use window.matchMedia instead of ResizeObserver for window size changes
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/global/globalConfig.ts
  src/ensembl/src/global/globalHelper.ts
  src/ensembl/src/global/windowSizeHelpers.ts
  src/ensembl/src/root/Root.test.tsx
  src/ensembl/src/root/Root.tsx
  src/ensembl/src/services/tests/storage-service.test.ts
  src/ensembl/src/services/window-service.ts
  src/ensembl/tests/mocks/mockWindowService.ts
Labels: refactoring

#216 Create 0014-visualisation-library.md
  src/ensembl/doc/architecture/decisions/0014-visualisation-library.md
Labels: documentation

#217 Add typescript optional chaining support and update packages
  src/ensembl/babel.config.js
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: infrastructure, package update

#171 PasteOrUpload component refactoring and storybook entry
  src/ensembl/src/content/app/custom-download/components/checkbox-with-textfields/CheckboxWithTextfields.scss
  src/ensembl/src/content/app/custom-download/components/checkbox-with-textfields/CheckboxWithTextfields.test.tsx
  src/ensembl/src/content/app/custom-download/components/checkbox-with-textfields/CheckboxWithTextfields.tsx
  src/ensembl/src/content/app/custom-download/components/content-builder/ContentBuilder.tsx
  src/ensembl/src/content/app/custom-download/components/paste-or-upload/PasteOrUpload.scss
  src/ensembl/src/content/app/custom-download/components/paste-or-upload/PasteOrUpload.test.tsx
  src/ensembl/src/content/app/custom-download/components/paste-or-upload/PasteOrUpload.tsx
  src/ensembl/src/content/app/custom-download/containers/header/customDownloadHeaderHelper.ts
  src/ensembl/src/content/app/custom-download/services/custom-download-storage-service.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItem.tsx
  src/ensembl/src/shared/components/accordion/helpers/uuid.test.ts
  src/ensembl/src/shared/components/accordion/index.tsx
  src/ensembl/src/shared/components/upload/Upload.scss
  src/ensembl/src/shared/components/upload/Upload.tsx
  src/ensembl/src/shared/helpers/generateId.test.ts
  src/ensembl/src/shared/helpers/generateId.ts
Labels: enhancement

#221 Update 0014-visualisation-library.md
  src/ensembl/doc/architecture/decisions/0014-visualisation-library.md
Labels: documentation

#205 Update the browser navigation panel according to the new designs
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.scss
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.test.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.scss
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.scss
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.test.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.test.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/global/globalHelper.ts
Labels: bugfix, enhancement

#223 Fix track panel opened on desktop rather than big desktop
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.test.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/global/globalConfig.ts
Labels: bugfix

#220 Add standard app layout
  src/ensembl/babel.config.js
  src/ensembl/package.json
  src/ensembl/src/shared/components/image-button/ImageButton.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/src/shared/components/layout/index.ts
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/layout/Layout.stories.scss
  src/ensembl/stories/shared-components/layout/Layout.stories.tsx
Labels: refactoring

#219 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: infrastructure, package update
