Repository Ensembl/ensembl-client, pull requests merged in 2019-11, with the labels that each got.

#145 Recently viewed bookmarks
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-genome-selector/BrowserGenomeSelector.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/browserState.ts
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerBookmarks.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerBookmarks.tsx
  src/ensembl/src/content/app/browser/drawer/drawerActions.ts
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-storage-service.test.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-storage-service.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.test.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelSelectors.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
  src/ensembl/src/styles/_breakpoints.scss
Labels: feature

#185 Upload component
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerBookmarks.scss
  src/ensembl/src/services/tests/storage-service.test.ts
  src/ensembl/src/services/window-service.ts
  src/ensembl/src/shared/components/upload/Upload.scss
  src/ensembl/src/shared/components/upload/Upload.test.tsx
  src/ensembl/src/shared/components/upload/Upload.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/upload/Upload.stories.scss
  src/ensembl/stories/shared-components/upload/Upload.stories.tsx
Labels: feature

#193 Prevent Sentry from recording ResizeObserver complaints
  src/ensembl/src/services/error-service.ts
Labels: housekeeping

#189 Add Chromosome navigator (mini-map)
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.scss
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/chromosomeNavigatorConstants.ts
  src/ensembl/src/content/app/browser/chromosome-navigator/chromosomeNavigatorHelper.ts
  src/ensembl/src/shared/helpers/textHelpers.ts
  src/ensembl/src/styles/_fonts.scss
  src/ensembl/src/styles/_settings.scss
  src/ensembl/static/fonts/ibm-plex-mono/ibm-plex-mono-v5-latin-regular.woff
  src/ensembl/static/fonts/ibm-plex-mono/ibm-plex-mono-v5-latin-regular.woff2
  src/ensembl/stories/design-primitives/colours/Colours.stories.tsx
  src/ensembl/stories/design-primitives/typography/Typography.stories.scss
  src/ensembl/stories/design-primitives/typography/Typography.stories.tsx
  src/ensembl/stories/genome-browser/chromosome-navigator/ChromosomeNavigator.stories.scss
  src/ensembl/stories/genome-browser/chromosome-navigator/ChromosomeNavigator.stories.tsx
  src/ensembl/stories/genome-browser/index.ts
  src/ensembl/stories/index.tsx
Labels: feature

#194 Remove IE11-specific code
  src/ensembl/package.json
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.scss
  src/ensembl/src/shared/components/tooltip/Tooltip.tsx
  src/ensembl/webpack/webpack.common.js
Labels: housekeeping

#197 Fix wasm build issues
  src/assets/browser/app/build/deploy.sh
  src/assets/browser/app/build/env.sh
Labels: bugfix

#196 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/drawer/drawerActions.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/header/headerActions.ts
  src/ensembl/src/header/headerReducer.ts
Labels: housekeeping, refactoring

#202 Update scss loading rules in webpack config
  src/ensembl/webpack/webpack.common.js
Labels: bugfix, housekeeping

#203 Move genome and ens-object folders to shared/state
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerGene.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerTranscript.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.tsx
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/content/home/homePageSelectors.ts
  src/ensembl/src/root/rootReducer.ts
  src/ensembl/src/shared/helpers/regionFormatter.ts
  src/ensembl/src/shared/state/ens-object/ensObjectActions.ts
  src/ensembl/src/shared/state/ens-object/ensObjectHelpers.ts
  src/ensembl/src/shared/state/ens-object/ensObjectReducer.ts
  src/ensembl/src/shared/state/ens-object/ensObjectSelectors.ts
  src/ensembl/src/shared/state/ens-object/ensObjectState.ts
  src/ensembl/src/shared/state/ens-object/ensObjectTypes.ts
  src/ensembl/src/shared/state/genome/genomeActions.ts
  src/ensembl/src/shared/state/genome/genomeReducer.ts
  src/ensembl/src/shared/state/genome/genomeSelectors.ts
  src/ensembl/src/shared/state/genome/genomeState.ts
  src/ensembl/src/shared/state/genome/genomeTypes.ts
  src/ensembl/tests/data/browser/karyotype.ts
  src/ensembl/tests/fixtures/ens-object.ts
  src/ensembl/tests/fixtures/genomes.ts
  src/ensembl/tests/fixtures/track-panel.ts
Labels: refactoring

#198 Fix tooltip width for Safari
  src/ensembl/src/shared/components/tooltip/Tooltip.scss
Labels: bugfix

#195 Browser Nav bar integration
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.test.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/chromosomeNavigatorConstants.ts
  src/ensembl/src/shared/data/centromeres.ts
  src/ensembl/src/shared/state/genome/genomeSelectors.ts
  src/ensembl/stories/genome-browser/chromosome-navigator/ChromosomeNavigator.stories.tsx
Labels: feature, refactoring

#201 Add tracking and stop bumping links to top after revisiting
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
Labels: enhancement

#204 hide placeholder on region field focus
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.scss
  src/ensembl/src/content/app/browser/zmenu/ZmenuController.tsx
Labels: enhancement

#181 Import genome browser static files from a github repository
  src/assets/browser/app/build/bin/build
  src/assets/browser/app/build/deploy.sh
  src/assets/browser/app/build/package.json
  src/assets/browser/app/build/prune-asset-repo.py
  src/assets/browser/app/build/prune-squasher.py
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/static/browser/browser-cc68e925924a545f48495c02d11045f1.wasm
  src/ensembl/static/browser/browser.js
  src/ensembl/webpack/webpack.config.dev.js
  src/ensembl/webpack/webpack.config.prod.js
Labels: git integration

#192 Add "counting" to blackbox functionality.
  src/assets/browser/app/src/data/blackbox/bbreportstream.rs
  src/assets/browser/app/src/data/blackbox/blackbox.rs
  src/assets/browser/app/src/data/blackbox/blackboxstate.rs
  src/assets/browser/app/src/data/blackbox/mod.rs
  src/assets/browser/app/src/util/macros.rs
Labels: enhancement

#188 Fix for ENSWBSITES-89 (turning tracks off doesn't turn labels off)
  src/assets/browser/app/src/composit/mod.rs
  src/assets/browser/app/src/composit/state.rs
  src/assets/browser/app/src/model/supply/productbuilder.rs
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: bugfix

#190 Boundary marker for location focused views
  src/assets/browser/app/src/composit/stick.rs
  src/assets/browser/app/src/drivers/webgl/core/glcarriage.rs
  src/assets/browser/app/src/model/stage/position.rs
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: bugfix

#191 Bugfix/perf traveller
  src/assets/browser/app/src/drivers/webgl/core/glprinter.rs
  src/assets/browser/app/src/drivers/webgl/core/gltraveller.rs
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: bugfix

#213 Create our own useResizeObserver hook
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.tsx
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/global/globalReducer.ts
  src/ensembl/src/root/Root.test.tsx
  src/ensembl/src/root/Root.tsx
  src/ensembl/src/services/tests/storage-service.test.ts
  src/ensembl/src/services/window-service.ts
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.tsx
  src/ensembl/src/shared/hooks/useResizeObserver.ts
  src/ensembl/static/html/template.html
  src/ensembl/tests/mocks/mockResizeObserver.ts
  src/ensembl/typings/ResizeObserver.d.ts
Labels: refactoring
