Repository Ensembl/ensembl-client, pull requests merged in 2019-05, with the labels that each got.

#39 Replace TSLint with ESLint
  src/ensembl/.eslintrc.js
  src/ensembl/README.md
  src/ensembl/doc/architecture/decisions/0006-coding-style.md
  src/ensembl/package.json
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/services/analytics-service.ts
  src/ensembl/src/services/api-service.ts
  src/ensembl/src/shared/accordion/components/ItemContext.tsx
  src/ensembl/src/shared/accordion/helpers/AccordionStore.ts
  src/ensembl/src/shared/privacy-banner/PrivacyBanner.tsx
  src/ensembl/tslint.json
  src/ensembl/webpack/webpack.common.js
Labels: enhancement

#47 Fix JavaScript issues in IE11
  src/ensembl/static/html/template.html
  src/ensembl/webpack/webpack.config.dev.js
Labels: bug, in-progress

#46 Feature/species tabs
  src/ensembl/src/shared/species-tab-bar/SpeciesTabBar.scss
  src/ensembl/src/shared/species-tab-bar/SpeciesTabBar.test.tsx
  src/ensembl/src/shared/species-tab-bar/SpeciesTabBar.tsx
  src/ensembl/src/shared/species-tab/SpeciesTab.scss
  src/ensembl/src/shared/species-tab/SpeciesTab.test.tsx
  src/ensembl/src/shared/species-tab/SpeciesTab.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/species-tab-bar/SpeciesTabBar.stories.scss
  src/ensembl/stories/shared-components/species-tab-bar/SpeciesTabBar.stories.tsx
  src/ensembl/stories/shared-components/species-tab-bar/juneSpeciesData.ts
  src/ensembl/stories/shared-components/species-tab-bar/speciesData.ts
Labels: enhancement

#50 Update genome selector location when browser location changes
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-genome-selector/BrowserGenomeSelector.tsx
Labels: bug

#54 Add error boundaries to avoid white screen of death
  src/ensembl/src/content/app/App.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/root/Root.tsx
  src/ensembl/src/services/error-service.ts
  src/ensembl/src/shared/error-boundary/ErrorBoundary.test.tsx
  src/ensembl/src/shared/error-boundary/ErrorBoundary.tsx
  src/ensembl/src/shared/error-screen/ErrorScreen.scss
  src/ensembl/src/shared/error-screen/GeneralErrorScreen.tsx
  src/ensembl/src/shared/error-screen/NewTechError.tsx
  src/ensembl/src/shared/error-screen/images/general-error-1.jpg
  src/ensembl/src/shared/error-screen/images/general-error-2.jpg
  src/ensembl/src/shared/error-screen/images/general-error-3.jpg
  src/ensembl/src/shared/error-screen/index.ts
Labels: enhancement

#55 [ENSWBSITES-119] Add new stylings to launchbar icons
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
Labels: enhancement
