Repository Ensembl/ensembl-client, pull requests merged in 2020-03, with the labels that each got.

#261 Add NOTICE and LICENSE
  LICENSE
  NOTICE
Labels: documentation

#264 Make sidebar slide over EV content view when open
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/stories/shared-components/layout/Layout.stories.tsx
Labels: enhancement

#265 Deploy feature branches to WP-HX
  .gitlab-ci.yml
Labels: infrastructure

#257 Add default transcripts list
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/_constants.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
Labels: feature

#266 Add the main README
  README.md
  src/ensembl/README.md
  src/ensembl/deploy.js
  src/ensembl/package.json
Labels: documentation

#260 Add default transcripts list layout to gene view of EV
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.test.tsx
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/static/img/shared/chevron-left.svg
  src/ensembl/static/img/shared/chevron-right.svg
Labels: feature

#271 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: package update

#268 Pluralisation formatter
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.test.tsx
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.test.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/browserHelper.ts
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/chromosomeNavigatorHelper.ts
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/FiltersAccordion.tsx
  src/ensembl/src/content/app/custom-download/containers/content/preview-download/PreviewDownload.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/shared/components/feature-summary-strip/GeneSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/RegionSummaryStrip.tsx
  src/ensembl/src/shared/helpers/formatters/numberFormater.test.ts
  src/ensembl/src/shared/helpers/formatters/numberFormatter.ts
  src/ensembl/src/shared/helpers/formatters/pluralisationFormatter.test.ts
  src/ensembl/src/shared/helpers/formatters/pluralisationFormatter.ts
  src/ensembl/src/shared/helpers/formatters/regionFormatter.ts
  src/ensembl/src/shared/helpers/formatters/strandFormatter.test.ts
  src/ensembl/src/shared/helpers/formatters/strandFormatter.ts
  src/ensembl/src/shared/state/ens-object/ensObjectTypes.ts
  src/ensembl/tests/fixtures/ens-object.ts
Labels: feature

#269 EntityViewer - Gene view tabs and panels
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar-tabs/GeneViewSidebarTabs.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-tabs/GeneViewTabs.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-tabs/GeneViewTabs.tsx
  src/ensembl/src/content/app/entity-viewer/state/entityViewerReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewActions.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/shared/components/tabs/Tabs.scss
Labels: enhancement

#274 Default sorting for transcripts list in EV gene view
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
Labels: feature
