Repository Ensembl/ensembl-client, pull requests merged in 2020-05, with the labels that each got.

#293 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/shared/helpers/environment.test.ts
Labels: package update

#292 EV sticky tabs and filter
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-tabs/GeneViewTabs.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
Labels: enhancement

#289 Protein list in entity viewer
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/_constants.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-gene-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-transcript-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/geneData.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/transcriptData.ts
  src/ensembl/src/content/app/entity-viewer/types/cds.ts
  src/ensembl/src/content/app/entity-viewer/types/product.ts
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
  src/ensembl/src/services/error-service.ts
  src/ensembl/stories/entity-viewer/protein/ProteinDomainImage.stories.tsx
  src/ensembl/stories/entity-viewer/transcripts/transcriptData.ts
  src/ensembl/tests/fixtures/entity-viewer/product.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: feature, refactoring

#290 Add cache to api-service
  src/ensembl/src/services/api-service.ts
  src/ensembl/src/services/tests/api-service.test.ts
  src/ensembl/src/shared/components/tabs/Tabs.test.tsx
  src/ensembl/src/shared/utils/lruCache.ts
  src/ensembl/src/shared/utils/tests/lruCache.test.ts
Labels: feature

#296 Fix CI/CD pipeline - Don't trigger subsequent job if dependent job(s) fail
  .gitlab-ci.yml
Labels: bugfix, infrastructure

#284 Use graphql api for EntityViewer topbar
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.test.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/GeneSummaryStrip.tsx
  src/ensembl/src/shared/state/ens-object/ensObjectHelpers.ts
Labels: refactoring

#282 Refactoring to support changed feature ids
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.test.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserHelper.ts
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerGene.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerTranscript.tsx
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelActions.ts
  src/ensembl/src/content/app/browser/zmenu/ZmenuAppLinks.tsx
  src/ensembl/src/content/app/browser/zmenu/ZmenuController.tsx
  src/ensembl/src/content/app/entity-viewer/EntityViewer.scss
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/example-links/ExampleLinks.scss
  src/ensembl/src/content/app/entity-viewer/components/example-links/ExampleLinks.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.test.tsx
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/GeneSummaryStrip.tsx
  src/ensembl/src/shared/helpers/urlHelper.ts
  src/ensembl/src/shared/state/ens-object/ensObjectActions.ts
  src/ensembl/src/shared/state/ens-object/ensObjectHelpers.ts
  src/ensembl/src/shared/state/ens-object/ensObjectSelectors.ts
  src/ensembl/src/shared/state/ens-object/ensObjectTypes.ts
  src/ensembl/src/shared/state/genome/genomeSelectors.ts
  src/ensembl/src/shared/state/genome/genomeTypes.ts
  src/ensembl/tests/fixtures/ens-object.ts
  src/ensembl/webpack/environments/webpack.config.dev.js
Labels: refactoring

#297 Get xrefs from thoas
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/src/content/app/entity-viewer/types/crossReference.ts
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
  src/ensembl/src/content/app/entity-viewer/types/source.ts
Labels: enhancement
