Repository Ensembl/ensembl-client, pull requests merged in 2020-06, with the labels that each got.

#301 Fix sidebar overview content and topbar tabs pointer
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.scss
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
Labels: bugfix

#302 Gene view function / relationships tabs availability
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.tsx
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewState.ts
Labels: enhancement

#254 ADR for auxiliary content
  src/ensembl/doc/architecture/decisions/0015-auxiliary-content.md
Labels: documentation

#307 Fix test of ChromosomeNavigator
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
Labels: bugfix

#306 Fix browser routing
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
Labels: bugfix

#308 Review apps for feature branch
  .gitlab-ci.yml
Labels: infrastructure

#311 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/webpack/environments/webpack.config.prod.js
Labels: package update

#309 Support view query parameter in EntityViewer url
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-tabs/GeneViewTabs.tsx
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewActions.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/entityViewerGeneViewState.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralSelectors.ts
  src/ensembl/src/shared/helpers/urlHelper.ts
Labels: feature

#310 Fix browser navigation bugs
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.scss
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
Labels: bugfix
