Repository Ensembl/ensembl-client, pull requests merged in 2020-10, with the labels that each got.

#351 Update StandardAppLayout
  src/ensembl/src/content/app/browser/Browser.scss
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-relationships/GeneRelationships.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/src/shared/components/layout/index.ts
  src/ensembl/src/styles/_scrollbars.scss
  src/ensembl/stories/shared-components/layout/Layout.stories.scss
  src/ensembl/stories/shared-components/layout/Layout.stories.tsx
Labels: refactoring

#363 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/stories/entity-viewer/transcripts/UnsplicedTranscripts.stories.tsx
Labels: housekeeping, package update

#360 Add SpeciesPageTitleArea
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainView.scss
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainView.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewTop.tsx
  src/ensembl/src/content/app/species/components/species-selection-controls/SpeciesSelectionControls.scss
  src/ensembl/src/content/app/species/components/species-selection-controls/SpeciesSelectionControls.tsx
  src/ensembl/src/content/app/species/components/species-title-area/SpeciesTitleArea.scss
  src/ensembl/src/content/app/species/components/species-title-area/SpeciesTitleArea.tsx
  src/ensembl/src/content/app/species/components/species-title-area/species-remove/SpeciesRemove.scss
  src/ensembl/src/content/app/species/components/species-title-area/species-remove/SpeciesRemove.test.tsx
  src/ensembl/src/content/app/species/components/species-title-area/species-remove/SpeciesRemove.tsx
  src/ensembl/src/content/app/species/components/species-title-area/species-usage-toggle/SpeciesUsageToggle.scss
  src/ensembl/src/content/app/species/components/species-title-area/species-usage-toggle/SpeciesUsageToggle.test.tsx
  src/ensembl/src/content/app/species/components/species-title-area/species-usage-toggle/SpeciesUsageToggle.tsx
  src/ensembl/src/shared/components/question-button/QuestionButton.scss
Labels: feature, refactoring

#352 Species homepage stats
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainView.scss
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainView.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/content/app/species/components/species-stats/SpeciesStats.scss
  src/ensembl/src/content/app/species/components/species-stats/SpeciesStats.tsx
  src/ensembl/src/content/app/species/sample-data.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralHelper.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralSelectors.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralSlice.ts
  src/ensembl/src/shared/components/expandable-section/ExpandableSection.scss
  src/ensembl/src/shared/components/expandable-section/ExpandableSection.test.tsx
  src/ensembl/src/shared/components/expandable-section/ExpandableSection.tsx
  src/ensembl/src/shared/components/view-in-app-popup/ViewInAppPopup.scss
  src/ensembl/src/shared/components/view-in-app-popup/ViewInAppPopup.tsx
  src/ensembl/stories/shared-components/expandable-section/ExpandableSection.stories.scss
  src/ensembl/stories/shared-components/expandable-section/ExpandableSection.stories.tsx
Labels: feature

#355 Do not mutate redux state for Custom Download
  src/ensembl/src/content/app/custom-download/components/content-builder/ContentBuilder.tsx
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/sections/orthologues/Orthologues.tsx
  src/ensembl/src/content/app/custom-download/state/attributes/attributesActions.ts
  src/ensembl/src/content/app/custom-download/state/customDownloadActions.ts
  src/ensembl/src/content/app/custom-download/state/filters/filtersActions.ts
Labels: bugfix

#368 Replace protein description placeholder with uniprot protein description
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/proteinData.ts
  src/ensembl/src/content/app/entity-viewer/types/externalReference.ts
  src/ensembl/src/content/app/entity-viewer/types/product.ts
Labels: enhancement

#365 Use ensembl-web deploy-tools image
  .gitlab-ci.yml
Labels: infrastructure

#370 Hide species page example links popup on production
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
Labels: enhancement

#367 Bugfixes after switching to Thoas
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/content/app/entity-viewer/types/crossReference.ts
  src/ensembl/src/content/app/entity-viewer/types/externalReference.ts
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
  src/ensembl/src/shared/components/checkbox/Checkbox.scss
  src/ensembl/tests/fixtures/entity-viewer/product.ts
Labels: bugfix

#371 Update popular species button behaviour
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.test.tsx
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/content/app/species-selector/containers/popular-species-panel/PopularSpeciesPanel.tsx
  src/ensembl/src/shared/helpers/urlHelper.ts
Labels: enhancement

#340 Add link to protein id in the transcript accordion
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/state/gene-view/proteins/geneViewProteinsSlice.ts
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/global/globalConfig.ts
  src/ensembl/src/global/globalReducer.ts
  src/ensembl/src/global/globalSelectors.ts
  src/ensembl/src/global/globalState.ts
  src/ensembl/src/shared/helpers/urlHelper.ts
  src/ensembl/src/shared/hooks/useRestoreScrollPosition.ts
Labels: enhancement

#372 Replace with species lozenge
  src/ensembl/src/content/app/App.tsx
  src/ensembl/src/content/app/browser/browser-app-bar/BrowserAppBar.tsx
  src/ensembl/src/content/app/custom-download/containers/app-bar/CustomDownloadAppBar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-app-bar/EntityViewerAppBar.tsx
  src/ensembl/src/content/app/species-selector/components/species-selector-app-bar/SpeciesSelectorAppBar.test.tsx
  src/ensembl/src/content/app/species-selector/components/species-selector-app-bar/SpeciesSelectorAppBar.tsx
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/content/app/species/components/species-app-bar/SpeciesAppBar.tsx
  src/ensembl/src/content/app/species/components/species-title-area/SpeciesTitleArea.tsx
  src/ensembl/src/content/home/components/homepage-species-bar/HomepageSpeciesBar.tsx
  src/ensembl/src/shared/components/new-selected-species/index.ts
  src/ensembl/src/shared/components/new-selected-species/selected-species-common.scss
  src/ensembl/src/shared/components/new-selected-species/selectedSpeciesHelpers.ts
  src/ensembl/src/shared/components/selected-species/FocusableSelectedSpecies.scss
  src/ensembl/src/shared/components/selected-species/FocusableSelectedSpecies.tsx
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.scss
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.test.tsx
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.tsx
  src/ensembl/src/shared/components/selected-species/SelectedSpeciesContent.tsx
  src/ensembl/src/shared/components/selected-species/SelectedSpeciesDisplayName.tsx
  src/ensembl/src/shared/components/selected-species/SimpleSelectedSpecies.scss
  src/ensembl/src/shared/components/selected-species/SimpleSelectedSpecies.tsx
  src/ensembl/src/shared/components/selected-species/index.ts
  src/ensembl/src/shared/components/species-tabs-wrapper/MultiLineSpeciesWrapper.scss
  src/ensembl/src/shared/components/species-tabs-wrapper/MultiLineSpeciesWrapper.tsx
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.tsx
  src/ensembl/src/shared/components/species-tabs-wrapper/speciesTabsWrapperHelpers.ts
  src/ensembl/stories/shared-components/selected-species/SelectedSpecies.stories.tsx
  src/ensembl/stories/shared-components/species-tabs-wrapper/SpeciesTabsWrapper.stories.tsx
Labels: enhancement

#364 Species page sidebar data
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/content/app/species/components/species-sidebar/SpeciesSidebar.scss
  src/ensembl/src/content/app/species/components/species-sidebar/SpeciesSidebar.tsx
  src/ensembl/src/content/app/species/sample-data.ts
  src/ensembl/src/content/app/species/state/sidebar/speciesSidebarSelectors.ts
  src/ensembl/src/content/app/species/state/sidebar/speciesSidebarSlice.ts
  src/ensembl/src/shared/components/external-link/ExternalLink.scss
  src/ensembl/src/shared/components/external-link/ExternalLink.test.tsx
  src/ensembl/src/shared/components/external-link/ExternalLink.tsx
  src/ensembl/src/shared/components/external-reference/ExternalReference.scss
  src/ensembl/src/shared/components/external-reference/ExternalReference.test.tsx
  src/ensembl/src/shared/components/external-reference/ExternalReference.tsx
Labels: enhancement, in progress

#369 Refactor Help&Docs popup
  src/ensembl/src/content/app/browser/browser-app-bar/BrowserAppBar.tsx
  src/ensembl/src/content/app/species-selector/components/species-selector-app-bar/SpeciesSelectorAppBar.tsx
  src/ensembl/src/shared/components/help-popup/HelpPopupBody.scss
  src/ensembl/src/shared/components/help-popup/HelpPopupBody.tsx
  src/ensembl/src/shared/components/help-popup/HelpPopupButton.tsx
  src/ensembl/src/shared/components/help-popup/types.ts
  src/ensembl/src/shared/components/help-popup/useHelpArticle.ts
  src/ensembl/src/shared/components/modal/Modal.scss
  src/ensembl/src/shared/hooks/useApiService.ts
Labels: enhancement

#377 Fix CloseButton — move onClick from cross icon to the button
  src/ensembl/src/shared/components/close-button/CloseButton.tsx
Labels: bugfix

#376 Show all committed species in the app bar on species page
  src/ensembl/src/content/app/species/components/species-app-bar/SpeciesAppBar.tsx
Labels: bugfix

#379 Fix checkbox styles in BrowserTrackConfig
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.scss
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
Labels: bugfix

#378 Update header topbar with new design
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.scss
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/header/Header.scss
  src/ensembl/src/header/Header.test.tsx
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.scss
  src/ensembl/src/header/header-buttons/HeaderButtons.test.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.tsx
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/src/shared/components/error-screen/ErrorScreen.scss
  src/ensembl/src/shared/components/error-screen/GeneralErrorScreen.tsx
  src/ensembl/src/shared/components/help-popup/HelpPopupButton.scss
  src/ensembl/src/shared/components/help-popup/HelpPopupButton.tsx
  src/ensembl/static/img/brand/logotype.svg
  src/ensembl/static/img/header/home.svg
  src/ensembl/static/img/launchbar/ensembl-logo.png
  src/ensembl/static/img/shared/info_circle.svg
Labels: enhancement

#382 Make sure that InlineSvg component can update properly
  src/ensembl/src/shared/components/inline-svg/InlineSvg.tsx
Labels: bugfix
