Repository Ensembl/ensembl-client, pull requests merged in 2020-04, with the labels that each got.

#278 Change url for toy graphql server
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
Labels: infrastructure

#277 Bring back the tooltip timeout
  src/ensembl/src/shared/components/tooltip/Tooltip.tsx
  src/ensembl/src/shared/components/tooltip/tooltip-constants.ts
Labels: bugfix

#281 Update packages
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: package update

#273 Default transcripts list content
  src/ensembl/src/content/app/browser/zmenu/ZmenuContent.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
  src/ensembl/src/shared/components/pointer-box/pointer-box-helper.ts
  src/ensembl/src/shared/components/toolbox/index.ts
  src/ensembl/tests/fixtures/entity-viewer/gene.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: feature

#249 Genome browser link component for entity viewer
  src/ensembl/src/content/app/browser/zmenu/ZmenuAppLinks.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/shared/components/view-in-app/ViewInApp.scss
  src/ensembl/src/shared/components/view-in-app/ViewInApp.test.tsx
  src/ensembl/src/shared/components/view-in-app/ViewInApp.tsx
Labels: feature

#276 Protein domain image
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.tsx
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-transcript-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/transcriptData.ts
  src/ensembl/src/content/app/entity-viewer/types/product.ts
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
  src/ensembl/stories/entity-viewer/index.ts
  src/ensembl/stories/entity-viewer/protein/ProteinDomainImage.stories.scss
  src/ensembl/stories/entity-viewer/protein/ProteinDomainImage.stories.tsx
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: feature

#275 Instant download
  src/ensembl/prettier.config.js
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
  src/ensembl/src/shared/components/button/Button.scss
  src/ensembl/src/shared/components/checkbox/Checkbox.scss
  src/ensembl/src/shared/components/checkbox/Checkbox.tsx
  src/ensembl/src/shared/components/instant-download/index.ts
  src/ensembl/src/shared/components/instant-download/instant-download-button/InstantDownloadButton.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForTranscript.ts
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscript.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscript.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.test.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.tsx
  src/ensembl/src/shared/helpers/downloadAsFile.ts
  src/ensembl/src/styles/_settings.scss
  src/ensembl/stories/shared-components/checkbox/Checkbox.stories.scss
  src/ensembl/stories/shared-components/checkbox/Checkbox.stories.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/instant-download/InstantDownload.stories.scss
  src/ensembl/stories/shared-components/instant-download/InstantDownload.stories.tsx
  src/ensembl/stories/shared-components/instant-download/InstantDownloadTranscript.stories.tsx
  src/ensembl/tests/fixtures/entity-viewer/gene.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: feature

#283 Add radio button to storybook
  src/ensembl/src/content/app/custom-download/components/checkbox-with-radios/CheckboxWithRadios.tsx
  src/ensembl/src/content/app/custom-download/components/content-builder/ContentBuilder.tsx
  src/ensembl/src/content/app/custom-download/types/Attributes.ts
  src/ensembl/src/shared/components/radio-group/RadioGroup.scss
  src/ensembl/src/shared/components/radio-group/RadioGroup.test.tsx
  src/ensembl/src/shared/components/radio-group/RadioGroup.tsx
  src/ensembl/src/shared/components/radio/Radio.scss
  src/ensembl/src/shared/components/radio/Radio.test.tsx
  src/ensembl/src/shared/components/radio/Radio.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/radio-group/RadioGroup.stories.tsx
Labels: feature

#286 Integrate instant download into default transcripts list
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.scss
Labels: feature
