Repository Ensembl/ensembl-client, pull requests merged in 2020-02, with the labels that each got.

#246 Fix the track panel bar button status
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
Labels: bugfix

#245 Entity viewer top bar showing the feature information
  .gitlab-ci.yml
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/EntityViewerTopbar.scss
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/EntityViewerTopbar.test.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.scss
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.tsx
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralState.ts
Labels: feature

#242 Create panel and tabs shared component
  src/ensembl/src/shared/components/panel/Panel.scss
  src/ensembl/src/shared/components/panel/Panel.test.tsx
  src/ensembl/src/shared/components/panel/Panel.tsx
  src/ensembl/src/shared/components/tabs/Tabs.scss
  src/ensembl/src/shared/components/tabs/Tabs.test.tsx
  src/ensembl/src/shared/components/tabs/Tabs.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/panel/Panel.stories.scss
  src/ensembl/stories/shared-components/panel/Panel.stories.tsx
  src/ensembl/stories/shared-components/tabs/Tabs.stories.scss
  src/ensembl/stories/shared-components/tabs/Tabs.stories.tsx
Labels: feature

#226 Replace svg with image button
  src/ensembl/src/content/app/browser/browser-cog/BrowserCog.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.tsx
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.scss
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
  src/ensembl/src/content/app/browser/browserConfig.ts
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/static/img/browser/icon_tracks_height.svg
  src/ensembl/static/img/browser/icon_tracks_highlight_grey.svg
  src/ensembl/static/img/browser/icon_tracks_lock_open_grey.svg
  src/ensembl/static/img/browser/icon_tracks_move.svg
  src/ensembl/static/img/browser/icon_tracks_move_grey.svg
  src/ensembl/static/img/browser/navigate-down-off.svg
  src/ensembl/static/img/browser/navigate-down.svg
  src/ensembl/static/img/browser/navigate-left-off.svg
  src/ensembl/static/img/browser/navigate-left.svg
  src/ensembl/static/img/browser/navigate-right-off.svg
  src/ensembl/static/img/browser/navigate-right.svg
  src/ensembl/static/img/browser/navigate-up-off.svg
  src/ensembl/static/img/browser/navigate-up.svg
  src/ensembl/static/img/browser/navigator-grey.svg
  src/ensembl/static/img/browser/navigator-selected.svg
  src/ensembl/static/img/browser/zoom-in-off.svg
  src/ensembl/static/img/browser/zoom-in.svg
  src/ensembl/static/img/browser/zoom-out-off.svg
  src/ensembl/static/img/browser/zoom-out.svg
  src/ensembl/static/img/shared/cog.svg
  src/ensembl/stories/shared-components/slide-toggle/SlideToggle.stories.tsx
Labels: enhancement

#248 Adding content and style to scale switcher
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.scss
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.tsx
Labels: feature

#244 Add BasePairsRuler
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/entity-viewer/components/base-pairs-ruler/BasePairsRuler.scss
  src/ensembl/src/content/app/entity-viewer/components/base-pairs-ruler/BasePairsRuler.test.tsx
  src/ensembl/src/content/app/entity-viewer/components/base-pairs-ruler/BasePairsRuler.tsx
  src/ensembl/src/content/app/entity-viewer/components/base-pairs-ruler/basePairsRulerHelper.test.ts
  src/ensembl/src/content/app/entity-viewer/components/base-pairs-ruler/basePairsRulerHelper.ts
  src/ensembl/stories/entity-viewer/base-pairs-ruler/BasePairsRuler.stories.scss
  src/ensembl/stories/entity-viewer/base-pairs-ruler/BasePairsRuler.stories.tsx
  src/ensembl/stories/entity-viewer/index.ts
  src/ensembl/stories/index.tsx
Labels: feature

#247 Add tracking for browser navigation inputs
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
Labels: enhancement

#250 Define & Use templates and improvement in CI/CD pipeline
  .gitlab-ci.yml
Labels: infrastructure

#243 Add entity viewer gene view
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-sidebar/EntityViewerSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/basePairsRulerHelper.test.ts
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/basePairsRulerHelper.ts
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar-tabs/GeneViewSidebarTabs.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar-tabs/GeneViewSidebarTabs.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-app-bar/EntityViewerAppBar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar-toolstrip/EntityViewerSidebarToolstrip.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.scss
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.test.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.scss
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/scale-switcher/ScaleSwitcher.tsx
  src/ensembl/stories/entity-viewer/base-pairs-ruler/BasePairsRuler.stories.tsx
Labels: feature

#259 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: package update

#251 Transcript image for entity viewer
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-gene-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-transcript-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/transcriptData.ts
  src/ensembl/src/content/app/entity-viewer/types/cds.ts
  src/ensembl/src/content/app/entity-viewer/types/exon.ts
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
  src/ensembl/src/content/app/entity-viewer/types/slice.ts
  src/ensembl/src/content/app/entity-viewer/types/strand.ts
  src/ensembl/src/content/app/entity-viewer/types/transcript.ts
  src/ensembl/stories/entity-viewer/index.ts
  src/ensembl/stories/entity-viewer/transcripts/UnsplicedTranscripts.stories.scss
  src/ensembl/stories/entity-viewer/transcripts/UnsplicedTranscripts.stories.tsx
  src/ensembl/stories/entity-viewer/transcripts/transcriptData.ts
  src/ensembl/tests/fixtures/entity-viewer/slice.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: feature

#256 Transcript filter for EV
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.scss
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.test.tsx
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.tsx
  src/ensembl/stories/entity-viewer/index.ts
  src/ensembl/stories/entity-viewer/transcript-filter/TranscriptFilter.stories.scss
  src/ensembl/stories/entity-viewer/transcript-filter/TranscriptFilter.stories.tsx
Labels: feature

#253 Gene overview image for EV
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
Labels: feature

#262 Refactor image button classes
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar-toolstrip/EntityViewerSidebarToolstrip.tsx
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.scss
  src/ensembl/src/header/header-buttons/HeaderButtons.tsx
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/components/visibility-icon/VisibilityIcon.tsx
Labels: refactoring

#263 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: package update
