Repository Ensembl/ensembl-client, pull requests merged in 2020-12, with the labels that each got.

#407 Add ADR for moving to React testing library, and migrate several test files from Enzyme
  src/ensembl/doc/architecture/decisions/0004-unit-tests.md
  src/ensembl/doc/architecture/decisions/0013-animation-library.md
  src/ensembl/doc/architecture/decisions/0016-react-testing-library.md
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/species/components/species-title-area/species-usage-toggle/SpeciesUsageToggle.test.tsx
  src/ensembl/src/shared/components/input/Input.test.tsx
  src/ensembl/src/shared/components/input/Input.tsx
  src/ensembl/src/shared/components/slide-toggle/SlideToggle.test.tsx
Labels: documentation

#408 Generalize parameter types in helper and sorter functions for transcripts
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/content/app/entity-viewer/types/slice.ts
Labels: enhancement

#406 Fix for transcript order to match default order same as in transcript image
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
Labels: enhancement

#405 Add label to the blue track representing the full protein in EntityViewer
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.tsx
Labels: enhancement

#412 Save sidebar open or closed state in session
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/content/app/species/services/species-storage-service.ts
  src/ensembl/src/content/app/species/state/sidebar/speciesSidebarSlice.ts
Labels: enhancement

#410 Display protein level xrefs
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
Labels: feature

#414 Use primary_id field from Ensembl REST response for protein xrefs for further querying
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/proteinData.ts
Labels: bugfix

#411 Fix messaging to genome browser during first-time navigation to genome brower page
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
Labels: bugfix

#416 Change the retry user message in protein list item
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
Labels: enhancement

#417 Expand function accordion by default
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/PublicationsAccordion.tsx
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/src/content/app/entity-viewer/types/publication.ts
Labels: enhancement

#420 Fix cannot set property expandedTranscriptIds of undefined
  src/ensembl/src/content/app/entity-viewer/state/gene-view/proteins/geneViewProteinsSlice.ts
Labels: bugfix

#421 Restyle the protein graphic for the download panel
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.tsx
Labels: enhancement, in progress

#423 Update tests to use react-testing-library
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-cog/BrowserCog.test.tsx
  src/ensembl/src/content/app/browser/browser-cog/BrowserCogList.test.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.test.tsx
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.test.tsx
  src/ensembl/src/global/windowSizeHelpers.ts
  src/ensembl/src/root/Root.test.tsx
  src/ensembl/src/root/Root.tsx
  src/ensembl/tests/mocks/mockWindowService.ts
Labels: refactoring

#419 Check if Uniprot ID exists on Interpro
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/proteinData.ts
Labels: enhancement

#427 Fix Species Selector search field
  src/ensembl/src/shared/components/input/Input.test.tsx
  src/ensembl/src/shared/components/input/Input.tsx
Labels: bugfix

#426 Add sort filter indicator to EV transcripts list
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
Labels: enhancement

#422 Retrieve gene data for gene overview from thoas
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
Labels: enhancement

#424 Add link to Europe PMC to Entity Viewer sidebar
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/publications/GenePublications.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/publications/GenePublications.tsx
Labels: feature
