Repository Ensembl/ensembl-client, pull requests merged in 2020-01, with the labels that each got.

#222 Refactor breakpoint width
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.test.tsx
  src/ensembl/src/content/app/browser/zmenu/Zmenu.test.tsx
  src/ensembl/src/global/globalActions.ts
  src/ensembl/src/global/globalHelper.ts
  src/ensembl/src/root/Root.tsx
  src/ensembl/src/shared/hooks/useResizeObserver.ts
Labels: refactoring

#225 Integrate StandardAppLayout in genome browser page
  src/ensembl/package.json
  src/ensembl/src/content/Content.scss
  src/ensembl/src/content/app/browser/Browser.scss
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.scss
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.scss
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.scss
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.test.tsx
  src/ensembl/src/content/app/browser/browser-location-indicator/BrowserLocationIndicator.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.scss
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.scss
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.test.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/drawer/Drawer.scss
  src/ensembl/src/content/app/browser/drawer/Drawer.test.tsx
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.scss
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.test.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.tsx
  src/ensembl/src/content/app/browser/zmenu/ZmenuContent.test.tsx
  src/ensembl/src/global/globalConfig.ts
  src/ensembl/src/global/globalState.ts
  src/ensembl/src/shared/components/app-bar/AppBar.scss
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.scss
  src/ensembl/src/shared/components/feature-summary-strip/GeneSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/RegionSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/index.ts
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.scss
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.tsx
  src/ensembl/src/shared/hooks/usePrevious.ts
  src/ensembl/src/styles/_normalize.scss
  src/ensembl/src/styles/main.scss
  src/ensembl/static/html/template.html
  src/ensembl/stories/shared-components/layout/Layout.stories.tsx
Labels: refactoring

#227 Fix ImageButton height by setting its font-size to 0
  src/ensembl/src/shared/components/image-button/ImageButton.scss
Labels: enhancement

#218 Use a dedicated component for toggle switch in BrowserTrackConfig panel
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.scss
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.test.tsx
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.tsx
  src/ensembl/src/shared/components/slide-toggle/SlideToggle.scss
  src/ensembl/src/shared/components/slide-toggle/SlideToggle.test.tsx
  src/ensembl/src/shared/components/slide-toggle/SlideToggle.tsx
  src/ensembl/stories/shared-components/index.ts
  src/ensembl/stories/shared-components/slide-toggle/SlideToggle.stories.tsx
Labels: enhancement, refactoring

#228 Add entity viewer app
  src/ensembl/src/content/app/App.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/entity-viewer/EntityViewer.scss
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-app-bar/EntityViewerAppBar.tsx
  src/ensembl/src/content/app/entity-viewer/state/entityViewerActions.ts
  src/ensembl/src/content/app/entity-viewer/state/entityViewerReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/entityViewerSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/entityViewerState.ts
  src/ensembl/src/global/globalConfig.ts
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/src/root/rootReducer.ts
  src/ensembl/src/shared/helpers/urlHelper.ts
  src/ensembl/src/shared/state/ens-object/ensObjectActions.ts
  src/ensembl/src/shared/state/ens-object/ensObjectSelectors.ts
  src/ensembl/static/img/launchbar/entity-viewer.svg
Labels: feature

#230 Update global layout and fix opening and closing of Launchbar
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/Content.scss
  src/ensembl/src/content/Content.tsx
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/header/account/Account.tsx
  src/ensembl/src/header/launchbar/Launchbar.test.tsx
  src/ensembl/src/header/launchbar/Launchbar.tsx
  src/ensembl/src/header/launchbar/LaunchbarContainer.tsx
  src/ensembl/src/root/Root.scss
  src/ensembl/src/styles/_animation.scss
  src/ensembl/src/styles/main.scss
Labels: bugfix, enhancement

#233 Refactor tooltip to place it immediately inside the body element
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.tsx
  src/ensembl/src/content/app/species-selector/components/popular-species-button/PopularSpeciesButton.tsx
  src/ensembl/src/content/app/species-selector/components/strain-selector/StrainSelector.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/components/question-button/QuestionButton.tsx
  src/ensembl/src/shared/components/tooltip/Tooltip.tsx
  src/ensembl/stories/shared-components/tooltip/positioningStory.tsx
  src/ensembl/stories/shared-components/tooltip/variantsStory.tsx
Labels: bugfix, enhancement

#234 Fix regex in failing test for ChromosomeNavigator
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
Labels: bugfix

#235 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
Labels: housekeeping, package update

#224 Add an option to disable opening/closing of accordion items
  src/ensembl/src/shared/components/accordion/components/AccordionItemButton.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItemButton.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItemHeading.tsx
  src/ensembl/src/shared/components/accordion/components/ItemContext.tsx
  src/ensembl/src/shared/components/accordion/css/Accordion.scss
  src/ensembl/stories/shared-components/accordion/Accordion.stories.scss
  src/ensembl/stories/shared-components/accordion/Accordion.stories.tsx
Labels: enhancement, in progress

#236 Update links to apps on home page to include entity viewer
  src/ensembl/src/content/home/Home.scss
  src/ensembl/src/content/home/Home.tsx
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.scss
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/content/home/components/homepage-site-info/HomepageSiteInfo.scss
  src/ensembl/src/content/home/components/homepage-site-info/HomepageSiteInfo.tsx
  src/ensembl/src/content/home/components/homepage-species-bar/HomepageSpeciesBar.scss
  src/ensembl/src/content/home/components/homepage-species-bar/HomepageSpeciesBar.tsx
Labels: feature

#232 Update styles for small screens
  src/ensembl/src/shared/components/app-bar/AppBar.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/styles/_scrollbars.scss
  src/ensembl/src/styles/main.scss
Labels: enhancement

#240 Remove runtime cache for service worker
  src/ensembl/webpack/environments/webpack.config.prod.js
Labels: bugfix

#237 Add tabs for EntityViewer sidebar
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-app-bar/EntityViewerAppBar.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-sidebar-tabs/EntityViewerSidebarTabs.scss
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-sidebar-tabs/EntityViewerSidebarTabs.tsx
  src/ensembl/src/content/app/entity-viewer/state/entityViewerReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/src/shared/types/status.ts
  src/ensembl/stories/shared-components/image-button/ImageButtonParent.stories.tsx
Labels: feature

#231 Refactor image button
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.test.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.test.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.scss
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/trackPanelConfig.ts
  src/ensembl/src/content/app/custom-download/containers/content/attributes-accordion/AttributesAccordion.tsx
  src/ensembl/src/content/app/custom-download/containers/content/filter-accordion/FiltersAccordion.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.test.tsx
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.test.tsx
  src/ensembl/src/header/header-buttons/HeaderButtons.tsx
  src/ensembl/src/header/launchbar/Launchbar.scss
  src/ensembl/src/header/launchbar/LaunchbarButton.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.scss
  src/ensembl/src/shared/components/image-button/ImageButton.test.tsx
  src/ensembl/src/shared/components/image-button/ImageButton.tsx
  src/ensembl/src/shared/components/image-button/ImageHolder.tsx
  src/ensembl/src/shared/components/visibility-icon/VisibilityIcon.scss
  src/ensembl/src/shared/components/visibility-icon/VisibilityIcon.test.tsx
  src/ensembl/src/shared/components/visibility-icon/VisibilityIcon.tsx
  src/ensembl/src/shared/types/status.ts
  src/ensembl/static/img/track-panel/eye-half.svg
  src/ensembl/stories/shared-components/badged-button/BadgedButton.stories.tsx
  src/ensembl/stories/shared-components/image-button/ImageButton.stories.tsx
  src/ensembl/stories/shared-components/image-button/ImageButtonParent.stories.tsx
  src/ensembl/tests/fixtures/ens-object.ts
  src/ensembl/tests/fixtures/track-panel.ts
Labels: refactoring

#241 Make BrowserInfo a shared component
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.test.tsx
  src/ensembl/src/content/app/browser/browser-bar/BrowserBar.tsx
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.test.tsx
  src/ensembl/src/shared/components/feature-summary-strip/FeatureSummaryStrip.tsx
  src/ensembl/src/shared/components/feature-summary-strip/RegionSummaryStrip.tsx
Labels: enhancement

#238 Entity viewer sidebar toolstrip
  src/ensembl/src/content/app/browser/Browser.scss
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBarIcon.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/trackPanelBarConfig.ts
  src/ensembl/src/content/app/entity-viewer/EntityViewer.scss
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-sidebar-toolstrip/EntityViewerSidebarToolstrip.tsx
  src/ensembl/src/content/app/entity-viewer/components/entity-viewer-sidebar/EntityViewerSideBar.tsx
  src/ensembl/src/header/Header.scss
  src/ensembl/src/header/Header.tsx
  src/ensembl/src/shared/components/error-screen/GeneralErrorScreen.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/static/img/sidebar/bookmark.svg
  src/ensembl/static/img/sidebar/download.svg
  src/ensembl/static/img/sidebar/own-data.svg
  src/ensembl/static/img/sidebar/search.svg
  src/ensembl/static/img/sidebar/share.svg
  src/ensembl/static/img/sidebar/tracks-manager.svg
  src/ensembl/stories/shared-components/badged-button/BadgedButton.stories.tsx
  src/ensembl/stories/shared-components/image-button/ImageButton.stories.tsx
  src/ensembl/stories/shared-components/layout/Layout.stories.scss
  src/ensembl/stories/shared-components/layout/Layout.stories.tsx
  src/ensembl/tests/fixtures/track-panel.ts
Labels: feature, refactoring
