Repository Ensembl/ensembl-client, pull requests merged in 2020-11, with the labels that each got.

#383 Update assembly dates to ISO YYYY-MM-DD format
  src/ensembl/src/content/app/species/sample-data.ts
Labels: bugfix

#384 Fix expanded transcript ids on new genes
  src/ensembl/src/content/app/entity-viewer/state/gene-view/transcripts/geneViewTranscriptsSlice.ts
Labels: bugfix

#386 Species tab (lozenge) design update
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.scss
Labels: enhancement

#385 Update gene symbol type and bookmarks example link text
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
Labels: enhancement

#373 Protein info error handling
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
Labels: enhancement

#387 open external links in new tab
  src/ensembl/src/shared/components/external-link/ExternalLink.tsx
Labels: enhancement

#389 Update entity viewer example links
  src/ensembl/src/content/app/browser/Browser.scss
  src/ensembl/src/content/app/entity-viewer/components/example-links/ExampleLinks.scss
  src/ensembl/src/content/app/entity-viewer/components/example-links/ExampleLinks.tsx
Labels: enhancement

#390 Support graphql refactoring (Strand moves from Region up to Slice)
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/types/slice.ts
  src/ensembl/tests/fixtures/entity-viewer/slice.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: enhancement

#388 AppShell not required anymore; css height fix
  src/ensembl/src/content/app/App.tsx
  src/ensembl/src/content/app/custom-download/CustomDownload.tsx
  src/ensembl/src/content/app/species-selector/SpeciesSelector.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
Labels: enhancement

#366 New shared mixin css
  src/ensembl/src/shared/components/round-button/RoundButton.scss
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.scss
  src/ensembl/src/shared/components/species-tabs-wrapper/SingleLineSpeciesWrapper.scss
  src/ensembl/src/styles/_mixins.scss
  src/ensembl/stories/shared-components/selected-species/SelectedSpecies.stories.tsx
Labels: enhancement

#393 Fix styles of selected species tab
  src/ensembl/src/shared/components/selected-species/SelectedSpecies.scss
Labels: bugfix

#392 Hide example links when the species is in Don't use state
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
Labels: enhancement

#391 Implement sorting and filtering of Transcript lists
  src/ensembl/package.json
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
  src/ensembl/src/content/app/entity-viewer/state/gene-view/transcripts/geneViewTranscriptsSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/transcripts/geneViewTranscriptsSlice.ts
Labels: feature

#397 Fix disabled species from getting accidentally deleted
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
Labels: bugfix

#396 Add storage service to species page to retain state
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/content/app/species/services/species-storage-service.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralSelectors.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralSlice.ts
  src/ensembl/src/services/storage-service.ts
  src/ensembl/src/services/tests/storage-service.test.ts
Labels: feature

#395 Image width constant
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/styles/_constants.scss
  src/ensembl/src/styles/_settings.scss
Labels: enhancement, in progress

#359 Add selected transcript to protein view
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/default-transcript-label/TranscriptQualityLabel.scss
  src/ensembl/src/content/app/entity-viewer/shared/components/default-transcript-label/TranscriptQualityLabel.tsx
Labels: feature, in progress

#394 Show only text for External Ref without URL
  src/ensembl/src/shared/components/external-reference/ExternalReference.scss
  src/ensembl/src/shared/components/external-reference/ExternalReference.tsx
Labels: bugfix

#402 Fix Safari external link icon bug
  src/ensembl/src/shared/components/external-link/ExternalLink.scss
Labels: bugfix

#398 Ensure species is enabled
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
Labels: bugfix
