Repository Ensembl/ensembl-client, pull requests merged in 2020-07, with the labels that each got.

#314 Add UniProt and PDBe IDs
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-features-count/ProteinFeaturesCount.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-adaptors/rest-protein-adaptor.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/proteinData.ts
  src/ensembl/stories/entity-viewer/protein/ProteinDomainImage.stories.tsx
Labels: feature, refactoring

#312 Client web thoas
  .gitlab-ci.yml
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/state/sidebar/sampleData.ts
  src/ensembl/webpack/environments/webpack.config.dev.js
Labels: enhancement

#318 Integrate toygraphql - Update URLs
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/webpack/environments/webpack.config.dev.js
Labels: in progress, infrastructure

#303 Adding filter and sort component to entity viewer
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.scss
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.test.tsx
  src/ensembl/src/content/app/entity-viewer/components/transcript-filter/EntityViewerTranscriptFilter.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
  src/ensembl/src/shared/components/checkbox/Checkbox.scss
  src/ensembl/src/shared/components/checkbox/Checkbox.test.tsx
  src/ensembl/src/shared/components/checkbox/Checkbox.tsx
  src/ensembl/src/shared/components/radio-group/RadioGroup.scss
  src/ensembl/src/shared/components/radio-group/RadioGroup.tsx
  src/ensembl/src/styles/_settings.scss
  src/ensembl/stories/design-primitives/colours/Colours.stories.tsx
  src/ensembl/stories/entity-viewer/index.ts
  src/ensembl/stories/entity-viewer/transcript-filter/TranscriptFilter.stories.scss
  src/ensembl/stories/entity-viewer/transcript-filter/TranscriptFilter.stories.tsx
  src/ensembl/stories/shared-components/checkbox/Checkbox.stories.scss
  src/ensembl/stories/shared-components/checkbox/Checkbox.stories.tsx
Labels: feature

#317 Protein sequence download
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForProtein.ts
  src/ensembl/src/shared/components/instant-download/instant-download-protein/InstantDownloadProtein.scss
  src/ensembl/src/shared/components/instant-download/instant-download-protein/InstantDownloadProtein.tsx
Labels: feature

#327 Update dependencies
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/components/example-links/ExampleLinks.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/webpack/presets/loadPresets.js
  src/ensembl/webpack/webpack.config.js
Labels: package update

#328 Add missing chromosome name in graphql query
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
Labels: bugfix

#325 Restore track states on browser refresh
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.test.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
Labels: bugfix

#329 Fix protein list sorting
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/content/app/entity-viewer/types/gene.ts
Labels: bugfix

#330 Use configureStore from redux-toolkit to set up redux store
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/store.ts
Labels: bugfix, refactoring
