Repository Ensembl/ensembl-client, pull requests merged in 2021-01, with the labels that each got.

#413 Preserve active species and entity in entity viewer
  src/ensembl/src/content/app/entity-viewer/services/entity-viewer-storage-service.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
Labels: enhancement

#425 Add sample regulation stats for human and mouse
  src/ensembl/src/content/app/species/sample-data.ts
  src/ensembl/src/content/app/species/state/general/speciesGeneralHelper.ts
Labels: enhancement

#428 Update tests to use react-testing-library
  src/ensembl/babel.config.js
  src/ensembl/jest.config.js
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBar.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarRegionSwitcher.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.test.tsx
  src/ensembl/src/content/app/browser/browser-region-editor/BrowserRegionEditor.test.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.test.tsx
  src/ensembl/src/content/app/browser/browser-region-field/BrowserRegionField.tsx
  src/ensembl/src/content/app/browser/browser-reset/BrowserReset.test.tsx
  src/ensembl/src/content/app/browser/browser-track-config/BrowserTrackConfig.test.tsx
  src/ensembl/src/content/app/browser/chromosome-navigator/ChromosomeNavigator.test.tsx
  src/ensembl/src/content/app/browser/track-panel/TrackPanel.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-bar/TrackPanelBar.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/TrackPanelModal.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-tabs/TrackPanelTabs.test.tsx
  src/ensembl/tests/setup-rtl.ts
Labels: refactoring

#429 Update Species Selector search field to use CloseButton
  src/ensembl/src/content/app/species-selector/components/selected-species/SelectedSpecies.scss
  src/ensembl/src/content/app/species-selector/components/selected-species/SelectedSpecies.test.tsx
  src/ensembl/src/content/app/species-selector/components/selected-species/SelectedSpecies.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.test.tsx
  src/ensembl/src/content/app/species-selector/components/species-search-field/SpeciesSearchField.tsx
  src/ensembl/src/content/app/species/SpeciesPage.scss
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/shared/components/clear-button/ClearButton.scss
  src/ensembl/src/shared/components/clear-button/ClearButton.tsx
  src/ensembl/src/shared/components/clear-button/cross.svg
  src/ensembl/src/shared/components/close-button/CloseButton.scss
  src/ensembl/src/shared/components/close-button/CloseButton.tsx
  src/ensembl/src/shared/components/close-button/close.svg
  src/ensembl/src/shared/components/question-button/QuestionButton.scss
  src/ensembl/src/shared/components/species-tabs-wrapper/MultiLineSpeciesWrapper.tsx
  src/ensembl/stories/shared-components/close-button/CloseButton.stories.tsx
Labels: bugfix, enhancement

#418 Genome browser brings back removed species
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-storage-service.test.ts
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-storage-service.test.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-storage-service.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelReducer.ts
  src/ensembl/src/content/app/species-selector/services/species-selector-storage-service.test.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/services/storage-service.ts
  src/ensembl/src/services/tests/storage-service.test.ts
  src/ensembl/src/shared/components/privacy-banner/privacy-banner-service.test.ts
Labels: bugfix

#430 Show only Swissprot description in gene function
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
Labels: enhancement

#433 Bring back the entity viewer sidebar accordion
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx
Labels: bugfix

#431 Fix hidden lozenges
  src/ensembl/src/root/Root.scss
Labels: bugfix

#441 ENSWBSITES-871: selected label rearrange when sorting apply
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
Labels: enhancement

#442 Add no-unneeded-ternary rule to ESLint
  src/ensembl/.eslintrc.js
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
Labels: enhancement

#443 Add padding to the right of contextual help article to show the scrollbar
  src/ensembl/src/shared/components/help-popup/HelpPopupBody.scss
Labels: bugfix

#444 Reorder protein list when transcripts are ordered
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
Labels: enhancement

#434 Cleanup ensObjects in entity viewer
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.test.tsx
  src/ensembl/src/content/app/entity-viewer/state/gene-view/proteins/geneViewProteinsSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/proteins/geneViewProteinsSlice.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/transcripts/geneViewTranscriptsSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/transcripts/geneViewTranscriptsSlice.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/view/geneViewViewSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/gene-view/view/geneViewViewSlice.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralState.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarReducer.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarSelectors.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
Labels: enhancement

#439 Use CloseButton component consistently
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.scss
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarMain.tsx
  src/ensembl/src/content/app/custom-download/components/info-card/CustomDownloadInfoCard.scss
  src/ensembl/src/content/app/custom-download/components/info-card/CustomDownloadInfoCard.tsx
  src/ensembl/src/content/app/custom-download/containers/content/preview-download/PreviewDownload.scss
  src/ensembl/src/content/app/custom-download/containers/content/preview-download/PreviewDownload.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.scss
  src/ensembl/src/shared/components/layout/StandardAppLayout.test.tsx
  src/ensembl/src/shared/components/layout/StandardAppLayout.tsx
  src/ensembl/src/shared/components/panel/Panel.scss
  src/ensembl/src/shared/components/panel/Panel.test.tsx
  src/ensembl/src/shared/components/panel/Panel.tsx
  src/ensembl/src/shared/components/toolbox/toolbox-expandable-content/ToolboxExpandableContent.scss
  src/ensembl/src/shared/components/toolbox/toolbox-expandable-content/ToolboxExpandableContent.tsx
  src/ensembl/static/img/shared/close.svg
Labels: enhancement
