Repository Ensembl/ensembl-client, pull requests merged in 2021-02, with the labels that each got.

#353 Add an ADR for server-side rendering
  src/ensembl/doc/architecture/decisions/0017-server-side-rendering.md
Labels: documentation

#435 Track descriptions
  src/ensembl/src/content/app/browser/drawer/Drawer.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerContigs.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/DrawerGC.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/OtherGenes.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/ProteinCodingGenes.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/SnpIndels.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/track-details/TrackDetails.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/track-details/TrackDetails.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/transcript-summary/TranscriptSummary.tsx
  src/ensembl/src/content/app/browser/drawer/drawerActions.ts
  src/ensembl/src/content/app/browser/drawer/drawerReducer.ts
  src/ensembl/src/content/app/browser/drawer/drawerSelectors.ts
  src/ensembl/src/content/app/browser/drawer/drawerState.ts
  src/ensembl/src/content/app/browser/drawer/sampleData.ts
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelList.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-list/TrackPanelListItem.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/shared/state/ens-object/ensObjectActions.ts
  src/ensembl/src/shared/state/ens-object/ensObjectTypes.ts
Labels: enhancement

#447 Improve sort and filter indicator for transcripts list
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
Labels: enhancement

#449 Enable Entity Viewer in production
  src/ensembl/src/content/app/browser/browser-app-bar/BrowserAppBar.tsx
  src/ensembl/src/content/app/browser/zmenu/ZmenuAppLinks.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/header/launchbar/Launchbar.tsx
Labels: enhancement

#436 Remove REST call to fetch UniProt ID
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/protein-list-constants.ts
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/proteinData.ts
Labels: enhancement

#445 Update Gene & Transcript drawer view to retrieve data from Thoas
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/drawer/Drawer.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/track-details/TrackDetails.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/transcript-summary/TranscriptSummary.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/transcript-summary/TranscriptSummary.tsx
  src/ensembl/src/content/app/browser/drawer/sampleData.ts
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/default-transcript-label/TranscriptQualityLabel.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-topbar/EntityViewerTopbar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/content/app/entity-viewer/shared/rest/rest-data-fetchers/transcriptData.ts
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscript.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscript.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.scss
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscriptVisualisation.tsx
  src/ensembl/src/shared/components/view-in-app/ViewInApp.tsx
  src/ensembl/src/shared/helpers/formatters/strandFormatter.test.ts
  src/ensembl/src/shared/helpers/formatters/strandFormatter.ts
  src/ensembl/src/shared/state/ens-object/ensObjectTypes.ts
  src/ensembl/src/shared/types/thoas/assembly.ts
  src/ensembl/src/shared/types/thoas/cdna.ts
  src/ensembl/src/shared/types/thoas/cds.ts
  src/ensembl/src/shared/types/thoas/dataSet.ts
  src/ensembl/src/shared/types/thoas/exon.ts
  src/ensembl/src/shared/types/thoas/externalReference.ts
  src/ensembl/src/shared/types/thoas/gene.ts
  src/ensembl/src/shared/types/thoas/homeologue.ts
  src/ensembl/src/shared/types/thoas/location.ts
  src/ensembl/src/shared/types/thoas/metadata.ts
  src/ensembl/src/shared/types/thoas/product.ts
  src/ensembl/src/shared/types/thoas/productGeneratingContext.ts
  src/ensembl/src/shared/types/thoas/slice.ts
  src/ensembl/src/shared/types/thoas/source.ts
  src/ensembl/src/shared/types/thoas/strand.ts
  src/ensembl/src/shared/types/thoas/transcript.ts
  src/ensembl/src/shared/types/thoas/utr.ts
Labels: enhancement, in progress

#453 Add eslint rule for equals operator
  src/ensembl/.eslintrc.js
  src/ensembl/src/content/app/custom-download/components/checkbox-with-selects/CheckboxWithSelects.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionContext.tsx
Labels: enhancement

#455 Handle empty uniprot xref in Entity Viewer protein view
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
Labels: bugfix

#452 Refactor the types of entities that we get from Thoas
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/transcript-summary/TranscriptSummary.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/default-transcripts-list-item/DefaultTranscriptListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-function/GeneFunction.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/ProteinsList.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item/ProteinsListItem.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/transcripts-filter/TranscriptsFilter.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/default-transcript-label/TranscriptQualityLabel.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/entity-helpers.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-sorter.ts
  src/ensembl/src/shared/types/thoas/cds.ts
  src/ensembl/src/shared/types/thoas/gene.ts
  src/ensembl/src/shared/types/thoas/homeologue.ts
  src/ensembl/src/shared/types/thoas/productGeneratingContext.ts
  src/ensembl/src/shared/types/thoas/transcript.ts
  src/ensembl/tests/fixtures/entity-viewer/gene.ts
  src/ensembl/tests/fixtures/entity-viewer/transcript.ts
Labels: refactoring

#459 Species specific sidebar state
  src/ensembl/src/content/app/species/SpeciesPage.tsx
  src/ensembl/src/content/app/species/state/sidebar/speciesSidebarSelectors.ts
  src/ensembl/src/content/app/species/state/sidebar/speciesSidebarSlice.ts
Labels: enhancement

#446 Fix focus entity on GB being stored in web browser history
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.tsx
  src/ensembl/src/content/app/browser/drawer/drawer-views/transcript-summary/TranscriptSummary.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.scss
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.test.tsx
  src/ensembl/src/content/app/browser/track-panel/track-panel-modal/modal-views/TrackPanelBookmarks.tsx
  src/ensembl/src/content/app/browser/zmenu/ZmenuAppLinks.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/GeneView.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/content/app/species/state/general/speciesGeneralHelper.ts
  src/ensembl/src/content/home/components/homepage-app-links/HomepageAppLinks.tsx
  src/ensembl/src/shared/components/view-in-app-popup/ViewInAppPopup.tsx
  src/ensembl/src/shared/components/view-in-app/ViewInApp.test.tsx
  src/ensembl/src/shared/components/view-in-app/ViewInApp.tsx
Labels: bugfix

#448 Use the common 'api/' namespace for different api endpoints
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserHelper.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorEpics.ts
  src/ensembl/src/gql-client.ts
  src/ensembl/src/shared/components/help-popup/useHelpArticle.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForProtein.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForTranscript.ts
  src/ensembl/src/shared/state/ens-object/ensObjectActions.ts
  src/ensembl/src/shared/state/genome/genomeActions.ts
  src/ensembl/webpack/environments/webpack.config.dev.js
Labels: enhancement

#463 Using back button with multiple species tabs for genome browser
  src/ensembl/src/content/app/browser/hooks/useBrowserRouting.ts
Labels: enhancement

#450 Download sequences in plain text and transform them to FASTA in web worker
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForProtein.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForTranscript.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchSequenceChecksums.ts
  src/ensembl/src/shared/helpers/formatters/fastaFormatter.test.ts
  src/ensembl/src/shared/helpers/formatters/fastaFormatter.ts
  src/ensembl/src/shared/workers/sequenceFetcher.worker.ts
  src/ensembl/webpack/environments/webpack.common.js
Labels: experiment, feature

#460 Fix region validation error
  src/ensembl/src/content/app/browser/browserHelper.ts
Labels: bugfix

#467 ENSWBSITES-959: remove sequence section in EV Right Hand panel
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/MainAccordion.tsx
Labels: enhancement

#466 ENSWBSITES-937: show "None" when there is no gene name and synonyms i…
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/overview/GeneOverview.tsx
Labels: enhancement
