Repository Ensembl/ensembl-client, pull requests merged in 2021-03, with the labels that each got.

#462 Filter stats within the helper
  src/ensembl/src/content/app/species/state/general/speciesGeneralHelper.ts
Labels: enhancement

#468 Reset genome browser track panel tabs on refresh
  src/ensembl/src/content/app/browser/browser-storage-service.ts
  src/ensembl/src/content/app/browser/track-panel/trackPanelState.ts
Labels: bugfix

#470 Species do not get removed from Entity Viewer
  src/ensembl/src/content/app/entity-viewer/services/entity-viewer-storage-service.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralActions.ts
  src/ensembl/src/content/app/entity-viewer/state/general/entityViewerGeneralReducer.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
Labels: bugfix

#473 Transcriptimage bugfix
  src/ensembl/src/content/app/entity-viewer/gene-view/components/base-pairs-ruler/BasePairsRuler.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-overview-image/GeneOverviewImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-domain-image/ProteinDomainImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/protein-image/ProteinImage.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.test.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/unspliced-transcript/UnsplicedTranscript.tsx
  src/ensembl/tests/fixtures/entity-viewer/gene.ts
Labels: bugfix

#474 Wrap transcript xrefs using accordion
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/external-references/GeneExternalReferences.tsx
Labels: enhancement

#475 Remove message and retry button for PDBe error responses
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.scss
  src/ensembl/src/content/app/entity-viewer/gene-view/components/proteins-list/proteins-list-item-info/ProteinsListItemInfo.tsx
Labels: enhancement

#471 Remove AssemblySelector from Species Selector
  src/ensembl/src/content/app/species-selector/components/assembly-selector/AssemblySelector.scss
  src/ensembl/src/content/app/species-selector/components/assembly-selector/AssemblySelector.test.tsx
  src/ensembl/src/content/app/species-selector/components/assembly-selector/AssemblySelector.tsx
  src/ensembl/src/content/app/species-selector/containers/species-search-panel/SpeciesSearchPanel.scss
  src/ensembl/src/content/app/species-selector/containers/species-search-panel/SpeciesSearchPanel.tsx
  src/ensembl/src/content/app/species-selector/state/speciesSelectorActions.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorReducer.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorSelectors.ts
  src/ensembl/src/content/app/species-selector/state/speciesSelectorState.ts
  src/ensembl/src/content/app/species-selector/types/species-search.ts
Labels: bugfix, enhancement

#465 Add transcript filter functionality to entity viewer
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/DefaultTranscriptsList.tsx
  src/ensembl/src/content/app/entity-viewer/shared/helpers/tests/transcripts-filter.test.ts
  src/ensembl/src/content/app/entity-viewer/shared/helpers/transcripts-filter.ts
Labels: feature

#479 Update accordion tests
  src/ensembl/src/shared/components/accordion/components/Accordion.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionContext.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItem.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItemButton.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItemHeading.test.tsx
  src/ensembl/src/shared/components/accordion/components/AccordionItemPanel.test.tsx
  src/ensembl/src/shared/components/accordion/components/ItemContext.test.tsx
Labels: enhancement

#456 Do not show arrow if summary and expanded stats have same content
  src/ensembl/src/content/app/species/components/species-main-view/SpeciesMainViewStats.tsx
  src/ensembl/src/content/app/species/state/general/speciesGeneralHelper.ts
Labels: enhancement

#477 Browser nav bar state update
  src/ensembl/src/content/app/browser/Browser.test.tsx
  src/ensembl/src/content/app/browser/Browser.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.test.tsx
  src/ensembl/src/content/app/browser/browser-image/BrowserImage.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavBarControls.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.test.tsx
  src/ensembl/src/content/app/browser/browser-nav/BrowserNavIcon.tsx
  src/ensembl/src/content/app/browser/browserActions.ts
  src/ensembl/src/content/app/browser/browserConfig.ts
  src/ensembl/src/content/app/browser/browserReducer.ts
  src/ensembl/src/content/app/browser/browserSelectors.ts
  src/ensembl/src/content/app/browser/browserState.ts
Labels: enhancement

#482 Loading button
  src/ensembl/src/shared/components/button/Button.scss
  src/ensembl/src/shared/components/loading-button/ControlledLoadingButton.tsx
  src/ensembl/src/shared/components/loading-button/LoadingButton.scss
  src/ensembl/src/shared/components/loading-button/LoadingButton.tsx
  src/ensembl/src/shared/components/loading-button/checkmark.svg
  src/ensembl/src/shared/components/loading-button/cross.svg
  src/ensembl/src/shared/components/loading-button/index.ts
  src/ensembl/stories/shared-components/loading-button/LoadingButton.stories.scss
  src/ensembl/stories/shared-components/loading-button/LoadingButton.stories.tsx
Labels: feature

#464 Instant download gene
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.scss
  src/ensembl/src/content/app/browser/drawer/drawer-views/gene-summary/GeneSummary.tsx
  src/ensembl/src/content/app/entity-viewer/EntityViewer.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/default-transcripts-list/transcripts-list-item-info/TranscriptsListItemInfo.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar-tabs/GeneViewSidebarTabs.tsx
  src/ensembl/src/content/app/entity-viewer/gene-view/components/gene-view-sidebar/GeneViewSideBar.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar/entity-viewer-sidebar-modal/modal-views/EntityViewerDownloads.scss
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar/entity-viewer-sidebar-modal/modal-views/EntityViewerDownloads.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar/entity-viewer-sidebar-modal/modal-views/PersonalData.tsx
  src/ensembl/src/content/app/entity-viewer/shared/components/entity-viewer-sidebar/entity-viewer-sidebar-toolstrip/EntityViewerSidebarToolstrip.tsx
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarActions.ts
  src/ensembl/src/content/app/entity-viewer/state/sidebar/entityViewerSidebarState.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForGene.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForProtein.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForTranscript.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchSequenceChecksums.ts
  src/ensembl/src/shared/components/instant-download/instant-download-gene/InstantDownloadGene.scss
  src/ensembl/src/shared/components/instant-download/instant-download-gene/InstantDownloadGene.tsx
  src/ensembl/src/shared/components/instant-download/instant-download-transcript/InstantDownloadTranscript.tsx
  src/ensembl/src/shared/helpers/formatters/fastaFormatter.test.ts
  src/ensembl/src/shared/helpers/formatters/fastaFormatter.ts
Labels: QA, feature

#362 Upgrade webpack to v5
  .gitlab-ci.yml
  src/ensembl/.eslintrc.js
  src/ensembl/.storybook/main.js
  src/ensembl/.storybook/webpack.js
  src/ensembl/Dockerfile
  src/ensembl/package-lock.json
  src/ensembl/package.json
  src/ensembl/robots-txt.config.js
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForProtein.ts
  src/ensembl/src/shared/components/instant-download/instant-download-fetch/fetchForTranscript.ts
  src/ensembl/static/robots.txt
  src/ensembl/webpack/environments/environment-detector.js
  src/ensembl/webpack/environments/webpack.common.js
  src/ensembl/webpack/environments/webpack.config.dev.js
  src/ensembl/webpack/environments/webpack.config.prod.js
  src/ensembl/webpack/presets/loadPresets.js
  src/ensembl/webpack/presets/webpack.analyse.js
  src/ensembl/webpack/webpack.config.js
Labels: housekeeping, infrastructure, package update
